apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/
  - services/
  - configmaps/
  - secrets/

commonLabels:
  app: city-lifestyle
  
configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=base
