apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  host: ${DB_HOST}
  port: "${DB_PORT}"
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
stringData:
  host: ${REDIS_HOST}
  port: "${REDIS_PORT}"
  password: ${REDIS_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  jwt-secret: ${JWT_SECRET}
