apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: city-lifestyle-prod
namePrefix: prod-

resources:
- ../../base
- monitoring.yaml
- ingress.yaml
- network-policies.yaml
- hpa.yaml

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - API_URL=https://api.citylifestyle.com
  - AUTH_URL=https://auth.citylifestyle.com
  - LOG_LEVEL=info
  - ENABLE_ANALYTICS=true
  - ENABLE_REAL_TIME_UPDATES=true

patches:
- path: resources-patch.yaml
  target:
    kind: Deployment
- path: storage-patch.yaml
  target:
    kind: PersistentVolumeClaim

images:
- name: frontend
  newName: ${DOCKER_REGISTRY}/citylife-frontend
  newTag: ${TAG}
- name: api
  newName: ${DOCKER_REGISTRY}/citylife-api
  newTag: ${TAG}
- name: auth
  newName: ${DOCKER_REGISTRY}/citylife-auth
  newTag: ${TAG}

replicas:
- name: frontend
  count: 3
- name: api
  count: 5
- name: auth
  count: 3
